"""常量定义"""

# Redis键前缀
REDIS_PREFIX = "cm"
DEVICE_PREFIX = "dev"
DICT_PREFIX = "dict"
INDEX_PREFIX = "idx"

# 设备状态
DEVICE_STATUS_ONLINE = "online"
DEVICE_STATUS_OFFLINE = "offline"
DEVICE_STATUS_MAINTENANCE = "maintenance"

# 订单状态
ORDER_STATUS_CREATED = "created"
ORDER_STATUS_PENDING = "pending"
ORDER_STATUS_PAID = "paid"
ORDER_STATUS_BREWING = "brewing"
ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_FAILED = "failed"
ORDER_STATUS_CANCELLED = "cancelled"

# 支付状态
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_TIMEOUT = "timeout"
PAYMENT_STATUS_CANCELLED = "cancelled"

# 制作状态
BREWING_STATUS_IDLE = "idle"
BREWING_STATUS_BREWING = "brewing"
BREWING_STATUS_COMPLETED = "completed"
BREWING_STATUS_FAILED = "failed"

# 命令类型
COMMAND_TYPE_BREW = "brew"
COMMAND_TYPE_OPEN_DOOR = "open_door"
COMMAND_TYPE_CLEAN = "clean"
COMMAND_TYPE_UPGRADE = "upgrade"
COMMAND_TYPE_SYNC = "sync"

# 命令状态
COMMAND_STATUS_PENDING = "pending"
COMMAND_STATUS_CLAIMED = "claimed"
COMMAND_STATUS_SUCCESS = "success"
COMMAND_STATUS_FAILED = "failed"

# 物料类型
MATERIAL_TYPE_BEAN = "bean"
MATERIAL_TYPE_POWDER = "powder"
MATERIAL_TYPE_LIQUID = "liquid"

# 物料代码
MATERIAL_BEAN_A = "BEAN_A"
MATERIAL_MILK_POWDER = "MILK_POWDER"
MATERIAL_SUGAR = "SUGAR"
MATERIAL_WATER = "WATER"

# 支付方式
PAYMENT_METHOD_WECHAT = "wechat"
PAYMENT_METHOD_ALIPAY = "alipay"

# 事件类型
EVENT_TYPE_PAY_UPDATE = "pay_update"
EVENT_TYPE_BREW_PROGRESS = "brew_progress"
EVENT_TYPE_BREW_DONE = "brew_done"
EVENT_TYPE_MATERIAL_UPDATE = "material_update"
EVENT_TYPE_COMMAND_CLAIMED = "command_claimed"
EVENT_TYPE_COMMAND_DONE = "command_done"
EVENT_TYPE_NET_STATUS = "net_status"
EVENT_TYPE_HEARTBEAT = "heartbeat"

# 错误代码
ERROR_CODE_DEVICE_BUSY = "DEVICE_BUSY"
ERROR_CODE_INSUFFICIENT_MATERIALS = "INSUFFICIENT_MATERIALS"
ERROR_CODE_PAYMENT_TIMEOUT = "PAYMENT_TIMEOUT"
ERROR_CODE_PAYMENT_FAILED = "PAYMENT_FAILED"
ERROR_CODE_BREWING_FAILED = "BREWING_FAILED"
ERROR_CODE_NETWORK_ERROR = "NETWORK_ERROR"
ERROR_CODE_DEVICE_OFFLINE = "DEVICE_OFFLINE"

# UI相关
UI_SCREENSAVER_TIMEOUT = 30  # 秒
UI_DONE_PAGE_DURATION = 10   # 秒
UI_PAYMENT_TIMEOUT = 300     # 秒

# 触控相关
TOUCH_TARGET_MIN_SIZE = 44   # px
TOUCH_FEEDBACK_DURATION = 150  # ms

# 日志级别
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# 审计事件类型
AUDIT_BOOT_OK = "boot_ok"
AUDIT_BOOT_INIT = "boot_init"
AUDIT_BOOT_FIXUP = "boot_fixup"
AUDIT_MAINTENANCE_LOGIN = "maintenance_login"
AUDIT_MAINTENANCE_LOGIN_FAILED = "maintenance_login_failed"
AUDIT_MAINTENANCE_LOGOUT = "maintenance_logout"
AUDIT_DOOR_OPENED = "door_opened"
AUDIT_CLEANING_STARTED = "cleaning_started"
AUDIT_WATER_TEST = "water_test"
AUDIT_FACTORY_RESET = "factory_reset"
AUDIT_BIN_UPDATED = "bin_updated"
AUDIT_BIN_CALIBRATED = "bin_calibrated"
AUDIT_SETTING_CHANGED = "setting_changed"
AUDIT_MANUAL_SYNC = "manual_sync"

# 默认配置值
DEFAULT_PIN = "0000"
DEFAULT_LOW_MATERIAL_THRESHOLD = 20
DEFAULT_ENABLE_QUEUE = False
DEFAULT_LANGUAGE = "zh-CN"
DEFAULT_FIRMWARE_VERSION = "1.0.0"

# 配方ID
RECIPE_AMERICANO = "201"
RECIPE_LATTE = "202"  
RECIPE_MOCHA = "203"

# 包ID
PACKAGE_DEFAULT = "pkg-001"

# 正则表达式
REGEX_ORDER_ID = r'^[a-zA-Z0-9\-]{8,64}$'
REGEX_DEVICE_ID = r'^[a-zA-Z0-9\-]{3,32}$'
REGEX_COMMAND_ID = r'^[a-zA-Z0-9\-]{8,64}$'

# 时间格式
DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"
DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"
ISO_FORMAT = "%Y-%m-%dT%H:%M:%S"

# HTTP状态码
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_NOT_FOUND = 404
HTTP_CONFLICT = 409
HTTP_INTERNAL_SERVER_ERROR = 500
